Library3/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library3;
using Microsoft.AspNetCore.Authorization;

namespace Library3.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;

        public BooksController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index(string? name)
        {
            ViewBag.bookNmae = name;
            var libraryContext = _context.Books.Include(b => b.Language);
            return View(await libraryContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id, string? name)
        {
            ViewBag.bookName = name;
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.Books
                .Include(b => b.Language)
                .FirstOrDefaultAsync(m => m.Id == id);

            var genrebook = from gb in _context.BookGenres
                            where gb.BookId == books.Id
                            select gb;
            List<Genres> genres = new List<Genres>();
            foreach(var gb in genrebook)
            {
                var gen = from g in _context.Genres
                          where g.Id == gb.GenreId
                          select g;
                foreach(var gn in gen)
                { genres.Add(gn); }
            }
            ViewData["genreName"] = genres;

            var authbook = from ab in _context.BookAuthors
                            where ab.BookId == books.Id
                            select ab;
            List<Authors> authors = new List<Authors>();
            foreach (var ab in authbook)
            {
                var auth = from a in _context.Authors
                          where a.Id == ab.AuthorId
                          select a;
                foreach (var au in auth)
                { authors.Add(au); }
            }
            ViewData["authorName"] = authors;

            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname");
            return View();
        }
        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id,PagesNum,LanguageId,Description")] Books books)
        {
            int counter = 0;
            foreach (var g in _context.Books)
            {
                if (g.Name == books.Name) { counter++; break; }
            }

            if (counter != 0)
            {
                ModelState.AddModelError("Name", "Таке ім'я вже існує");
                ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname", books.LanguageId);
                return View(books);
            } else
            {
                if (books.PagesNum < 0)
                {
                    ModelState.AddModelError("PagesNum", "Кількість сторінок понна бути додатня!");
                    ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname", books.LanguageId);
                    return View(books);
                }
                else
                {

                    if (ModelState.IsValid)
                    {
                        _context.Add(books);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname", books.LanguageId);
                    return View(books);
                }
            }
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.Books.FindAsync(id);
            if (books == null)
            {
                return NotFound();
            }
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname", books.LanguageId);
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,PagesNum,LanguageId,Description")] Books books)
        {
            if (id != books.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(books);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BooksExists(books.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Lname", books.LanguageId);
            return View(books);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _context.Books
                .Include(b => b.Language)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var books = await _context.Books.FindAsync(id);
            var booksgenre = from bg in _context.BookGenres
                             where bg.BookId == books.Id
                             select bg;
            foreach(var bg in booksgenre)
            {
                _context.BookGenres.Remove(bg);
            }
            var booksauthor = from ba in _context.BookAuthors
                              where ba.BookId == books.Id
                              select ba;
            foreach (var ba in booksauthor)
            {
                _context.BookAuthors.Remove(ba);
            }
            _context.Books.Remove(books);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BooksExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }
    }
}

Library3/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Library3.Models;
using Library3.ViewModel;
using System.ComponentModel.DataAnnotations;

namespace Library3.Controllers
{
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();


        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Name = model.Name, UserName = model.Name, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Name = user.Name, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Name = model.Name;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Name = user.Name };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }

    }
}

Library3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
        <link rel="shortcut icon" href="~/images/book.png" type="image/png">
    
    <title>@ViewData["Title"] YourLibrary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light myheader mb-3">
            <div class="container">
                <a class=" librarytext nav-link " asp-controller="Home" asp-action="Index">YourLibrary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="homebtn mytext" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="homebtn mytext" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="homebtn mytext" asp-area="" asp-controller="Authors" asp-action="Index">Authors</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="homebtn mytext" asp-area="" asp-controller="Home" asp-action="Privacy">  Privacy</a>
                            </li>
                        }
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a style="margin-right:80px" class="mytext enter" asp-controller="Users" asp-action="Index">@User.Identity.Name</a>

                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class="mytext knopka_logout" type="submit" value="Вихід" />
                                </form>
                            }
                            else
                            {
                                <a class="mytext enter" asp-controller="Account" asp-action="Login">Вхід</a>
                                <a class="mytext reg" asp-controller="Account" asp-action="Register">Реєстація</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom:72px; z-index:1">
        <main role="main" class="kvadrat alltext" style="color: rgb(236, 210, 185)">
            <div>
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            &copy; 2020 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>