Library3/Models/BookGenres.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Library3
{
    public partial class BookGenres
    {
        public int Id { get; set; }
        public int? GenreId { get; set; }
        public int? BookId { get; set; }

        [Display(Name = "Книжка")]
        public virtual Books Book { get; set; }

        [Display(Name = "Жанр")]
        public virtual Genres Genre { get; set; }
    }
}

Library3/Controllers/BookAuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library3;

namespace Library3.Controllers
{
    public class BookAuthorsController : Controller
    {
        private readonly LibraryContext _context;

        public BookAuthorsController(LibraryContext context)
        {
            _context = context;
        }

        // GET: BookAuthors
        public async Task<IActionResult> Index(int? id, string? name)
        {
            ViewBag.authorName = name;
            ViewBag.authorId = id;
            var libraryContext = _context.BookAuthors
                .Where(b => b.AuthorId == id)
                .Include(b => b.Author)
                .Include(b => b.Book)
                .Include(b => b.Book.Language);
            return View(await libraryContext.ToListAsync());
        }

        // GET: BookAuthors/Details/5
        public async Task<IActionResult> Details(int? id, string? name)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var bookAuthors = await _context.BookAuthors
                .Include(b => b.Author)
                .Include(b => b.Book)
                .Include(b => b.Book.Language)
                .FirstOrDefaultAsync(m => m.Id == id);
            var bgenr = from bg in _context.BookGenres
                        where bg.BookId == bookAuthors.BookId
                        select bg;
            List<Genres> genres = new List<Genres>();

            foreach (var bg in bgenr)
            {
                var genr = from g in _context.Genres
                           where g.Id == bg.GenreId
                           select g;
                foreach (var gen in genr)
                {
                    genres.Add(gen);
                }
            }
            ViewData["genreName"] = genres;

            var authbook = from ab in _context.BookAuthors
                           where ab.BookId == bookAuthors.BookId
                           select ab;
            List<Authors> authors = new List<Authors>();
            foreach (var ab in authbook)
            {
                var auth = from a in _context.Authors
                           where a.Id == ab.AuthorId
                           select a;
                foreach (var au in auth)
                { authors.Add(au); }
            }
            ViewData["authorName"] = authors;

            ViewBag.bookName = bookAuthors.Book.Name;
            if (bookAuthors == null)
            {
                return NotFound();
            }

            return View(bookAuthors);
        }

        // GET: BookAuthors/Create
        public IActionResult Create(int? id)
        {
            ViewBag.authorId = id;
            //ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "AuthorName");
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name");
            return View();
        }

        // POST: BookAuthors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int authorId,[Bind("Id,BookId")] BookAuthors bookAuthors)
        {
            BookAuthors ba = new BookAuthors();
            ba.AuthorId = authorId;
            bookAuthors.AuthorId = authorId;
            ba.BookId = bookAuthors.BookId;
            if (ModelState.IsValid)
            {
                _context.Add(ba);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = authorId });
            }
            //ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "AuthorName", bookAuthors.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookAuthors.BookId);
            return View("Index", new { id = authorId });
        }

        // GET: BookAuthors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookAuthors = await _context.BookAuthors.FindAsync(id);
            if (bookAuthors == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "AuthorName", bookAuthors.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookAuthors.BookId);
            return View(bookAuthors);
        }

        // POST: BookAuthors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookId,AuthorId")] BookAuthors bookAuthors)
        {
            if (id != bookAuthors.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookAuthors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookAuthorsExists(bookAuthors.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "AuthorName", bookAuthors.AuthorId);
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookAuthors.BookId);
            return View(bookAuthors);
        }

        // GET: BookAuthors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookAuthors = await _context.BookAuthors
                .Include(b => b.Author)
                .Include(b => b.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookAuthors == null)
            {
                return NotFound();
            }

            return View(bookAuthors);
        }

        // POST: BookAuthors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookAuthors = await _context.BookAuthors.FindAsync(id);
            _context.BookAuthors.Remove(bookAuthors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookAuthorsExists(int id)
        {
            return _context.BookAuthors.Any(e => e.Id == id);
        }
    }
}

Library3/Controllers/BookGenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library3;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using System.IO;
using Spire.Doc;
using Spire.Doc.Documents;
using System.Drawing;


namespace Library3.Controllers
{
    public class BookGenresController : Controller
    {
        private readonly LibraryContext _context;

        public BookGenresController(LibraryContext context)
        {
            _context = context;
        }

        // GET: BookGenres
        public async Task<IActionResult> Index(int? id, string? name)
        {
            ViewBag.genreName = name;
            ViewBag.genreId = id;
            var libraryContext = _context.BookGenres
                .Where(b => b.GenreId == id)
                .Include(b => b.Book)
                .Include(b => b.Genre)
                .Include(b=> b.Book.Language);
            return View(await libraryContext.ToListAsync());
        }

        // GET: BookGenres/Details/5
        public async Task<IActionResult> Details(int? id, string? name)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var bookGenres = await _context.BookGenres
                .Include(b => b.Book)
                .Include(b => b.Genre)
                .Include(b=>b.Book.Language)
                .FirstOrDefaultAsync(m => m.Id == id);
            var bauth = from ba in _context.BookAuthors
                        where ba.BookId == bookGenres.BookId
                        select ba;
            List<Authors> authors = new List<Authors>();

            foreach(var ba in bauth)
            {
                var auth = from a in _context.Authors
                           where a.Id == ba.AuthorId
                           select a;
                foreach(var au in auth)
                {
                    authors.Add(au);
                }
            }
            ViewData["authorName"] = authors;

            var genrebook = from gb in _context.BookGenres
                            where gb.BookId == bookGenres.BookId
                            select gb;
            List<Genres> genres = new List<Genres>();
            foreach (var gb in genrebook)
            {
                var gen = from g in _context.Genres
                          where g.Id == gb.GenreId
                          select g;
                foreach (var gn in gen)
                { genres.Add(gn); }
            }
            ViewData["genreName"] = genres;

            ViewBag.bookName = bookGenres.Book.Name;
            if (bookGenres == null)
            {
                return NotFound();
            }

            return View(bookGenres);
        }

        // GET: BookGenres/Create
        public IActionResult Create(int? id)
        {
            ViewBag.genreId = id;
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name");
            //ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name");
            return View();
        }

        // POST: BookGenres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int genreId, [Bind("Id,BookId")] BookGenres bookGenres)
        {
            BookGenres bg = new BookGenres();
            bg.GenreId = genreId;
            bookGenres.GenreId = genreId;
            bg.BookId = bookGenres.BookId;

            if (ModelState.IsValid)
            {
                _context.Add(bg);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = genreId});
            }
            //ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookGenres.BookId);
            //ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", bookGenres.GenreId);
            return RedirectToAction("Index", new { id = genreId });
        }

        // GET: BookGenres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookGenres = await _context.BookGenres.FindAsync(id);
            if (bookGenres == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookGenres.BookId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", bookGenres.GenreId);
            return View(bookGenres);
        }

        // POST: BookGenres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenreId,BookId")] BookGenres bookGenres)
        {
            if (id != bookGenres.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookGenres);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookGenresExists(bookGenres.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Name", bookGenres.BookId);
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", bookGenres.GenreId);
            return View(bookGenres);
        }

        // GET: BookGenres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookGenres = await _context.BookGenres
                .Include(b => b.Book)
                .Include(b => b.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookGenres == null)
            {
                return NotFound();
            }

            return View(bookGenres);
        }

        // POST: BookGenres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookGenres = await _context.BookGenres.FindAsync(id);
            _context.BookGenres.Remove(bookGenres);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookGenresExists(int id)
        {
            return _context.BookGenres.Any(e => e.Id == id);
        }

        ///////////////////////////////////////////////////////////
        public ActionResult Export(string name, int? id)
        {
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var genres = _context.BookGenres.Include(b=>b.Book).Include(l=>l.Book.Language).ToList();
                
                    var worksheet = workbook.Worksheets.Add(name);

                    worksheet.Cell("A1").Value = "Назва";
                    worksheet.Cell("B1").Value = "Мова";
                    worksheet.Cell("C1").Value = "К-ть сторінок";
                    worksheet.Cell("D1").Value = "Автор(и)";
                    worksheet.Row(1).Style.Font.Bold = true;
                    var bookgenres = from bookgen in _context.BookGenres
                                where bookgen.GenreId == id
                                select bookgen;
                    List<Books> books = new List<Books>();
                    foreach(var b in bookgenres)
                    {
                        var book = from boo in _context.Books
                                   where boo.Id == b.BookId
                                   select boo;
                        foreach (var bo in book)
                        { books.Add(bo); }
                    }

                    //нумерація рядків/стовпчиків починається з індекса 1 (не 0)
                    for (int i = 0; i < books.Count; i++)
                    {
                    worksheet.Cell(i + 2, 1).Value = books[i].Name;
                    worksheet.Cell(i + 2, 2).Value = books[i].Language.Lname;
                    worksheet.Cell(i + 2, 3).Value = books[i].PagesNum;

                        var ab = _context.BookAuthors.Where(a => a.BookId == books[i].Id).Include("Author").ToList();
                        
                        foreach (var a in ab)
                        {
                                worksheet.Cell(i + 2, 4).Value = a.Author.AuthorName;
                        }

                    }
                
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    stream.Flush();

                    return new FileContentResult(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        FileDownloadName = $"library_{DateTime.UtcNow.ToShortDateString()}.xlsx"
                    };
                }
            }
        }
        ////////////////////////////////////
        public ActionResult ExportDocx(string name, int? id)
        {

Library3/Views/BookGenres/Create.cshtml
@model Library3.BookGenres

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookGenres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" value="@ViewBag.genreId" name="GenreId"/> 
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class ="form-control" asp-items="ViewBag.BookId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library3/Views/BookGenres/Delete.cshtml
@model Library3.BookGenres

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookGenres</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Library3/Views/BookGenres/Details.cshtml
@model Library3.BookGenres

@{
    ViewData["Title"] = "Book - ";
}

<h1>@ViewBag.bookName</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookAuthors)
        </dt>
        <dd class="col-sm-10">
            @foreach (var auth in ViewData["authorName"] as List<Authors>)
            {

                @Html.ActionLink(@auth.AuthorName, "Index", "BookAuthors", new { id = auth.Id, name = auth.AuthorName })
                <a> </a>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.BookGenres)
        </dt>
        <dd class="col-sm-10">
            @foreach (var auth in ViewData["genreName"] as List<Genres>)
            {

                @Html.ActionLink(@auth.Name, "Index", "BookGenres", new { id = auth.Id, name = auth.Name })
                <a> </a>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Language)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Language.Lname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.PagesNum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.PagesNum)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Book.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("admin"))
    {<a asp-action="Edit" asp-route-id="@Model.Id">Edit |</a>}
@Html.ActionLink("Back to list", "Index", new { id = Model.Genre.Id, name = Model.Genre.Name })
</div>

Library3/Views/BookGenres/Edit.cshtml
@model Library3.BookGenres

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookGenres</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library3/Views/BookGenres/Index.cshtml
@model IEnumerable<Library3.BookGenres>

@{
    ViewData["Title"] = @ViewBag.genreName + " - ";
}

<h1>@ViewBag.genreName</h1>
@if (User.IsInRole("admin"))
{ 
    <p>
        @Html.ActionLink("Create", "Create", new { id = ViewBag.genreId })
    </p>
 }
<div>
    <h3>
        Завантаження інформації про книжки жанру "@ViewBag.genreName" в .xlsx файл:
        @Html.ActionLink("Download", "Export", new { name = ViewBag.genreName, id = ViewBag.genreId })
        | в .docx файл:
        @Html.ActionLink("Download", "ExportDocx", new { name = ViewBag.genreName, id = ViewBag.genreId })
    </h3>
</div>
@*<div>
    <h3>| в .docx файл:
        @Html.ActionLink("Download", "ExportDocx", new { name = ViewBag.genreName, id = ViewBag.genreId })
    </h3>
</div>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Book)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Book.Name)
                </td>

                <td class="td">
                    @if (User.IsInRole("admin"))
                    {

                        <a asp-action="Edit" asp-route-id="@item.Id">Edit |</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete |</a>
                    }
                    @Html.ActionLink("Book", "Details", new { id = item.Id, name = item.Book.Name, num = item.Book.PagesNum })
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="container">
    <div id="chart1"></div>
</div>



@section scripts{
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script>
        google.charts.load('current', { 'packeges': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {
            $.get('/api/Charts/JsonData', function (jsonData) {
                data = google.visualization.arrayToDataTable(jsondata, false);
                var option = {
                    title: "Співвідношення кількості книжок та мов",
                    width: 500, height: 400
                };
                chart = new google.visualization.PieChart(document.getElementById('chart1'));
            })
        }
    </script>
}